[target.aarch64-unknown-linux-musl]
rustflags = ["-Clink-arg=-fuse-ld=lld"]

[target.armv7-unknown-linux-musleabihf]
rustflags = ["-Clink-arg=-fuse-ld=lld"]

[target.x86_64-unknown-linux-musl]
rustflags = ["-Clink-arg=-fuse-ld=lld"]

