name: Rust Build and Test

on:
  push:
    branches: [ main ]
    paths:
      - .github/workflows/build.yml
      - src/**
      - test/**
      - Cargo.lock
      - Cargo.toml
  pull_request:
    branches: [ main ]
    paths:
      - .github/workflows/build.yml
      - src/**
      - test/**
      - Cargo.lock
      - Cargo.toml
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  bin-name: qstract

permissions: { }

jobs:
  build-versions:
    strategy:
      fail-fast: false
      matrix:
        rust-version: [ stable, nightly, 1.85 ] # Stable, Beta, Nightly, MSRV
        info:
          - os: macos-latest
            target1: aarch64-apple-darwin
            target2: x86_64-apple-darwin
          - os: ubuntu-latest
            target1: x86_64-unknown-linux-gnu
            target2: i686-unknown-linux-gnu
          - os: windows-latest
            target1: x86_64-pc-windows-msvc
            target2: i686-pc-windows-msvc
    runs-on: ${{ matrix.info.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: dtolnay/rust-toolchain@master
        id: toolchain
        with:
          toolchain: ${{ matrix.rust-version }}
          targets: ${{ matrix.info.target1 }},${{ matrix.info.target2 }}
          components: rust-src
      - uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.info.target1 }}+${{ matrix.info.target2 }}
      - name: Build (1)
        run: cargo +${{steps.toolchain.outputs.name}} build --verbose --workspace --target ${{ matrix.info.target1 }}
      - name: Build (2)
        run: cargo +${{steps.toolchain.outputs.name}} build --verbose --workspace --target ${{ matrix.info.target2 }}
      - name: Artifact (1)
        if: ${{ matrix.rust-version == 'nightly' }}
        uses: actions/upload-artifact@v4
        with:
          name: target-na-${{ matrix.target1 }}
          path: |
            target/${{ matrix.target1 }}/debug/${{ env.bin-name }}
      - name: Artifact (2)
        if: ${{ matrix.rust-version == 'nightly' }}
        uses: actions/upload-artifact@v4
        with:
          name: target-na-${{ matrix.target2 }}
          path: |
            target/${{ matrix.target2 }}/debug/${{ env.bin-name }}

  build-ink-cross:
    strategy:
      matrix:
        rust-version: [ nightly ]
        info:
          - target: aarch64-unknown-linux-gnu
          - target: aarch64-unknown-linux-musl
          - target: armv7-unknown-linux-gnueabihf
          - target: armv7-unknown-linux-musleabihf
          - target: powerpc64le-unknown-linux-gnu
          - target: powerpc64-unknown-linux-gnu
          - target: riscv64gc-unknown-linux-gnu
          - target: s390x-unknown-linux-gnu
          - target: x86_64-unknown-linux-gnu
          - target: x86_64-unknown-linux-musl
          - target: x86_64-unknown-freebsd
          - target: x86_64-unknown-netbsd
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: Swatinem/rust-cache@v2
        with:
          key: ink-build-${{ matrix.info.target }}
      - name: Permission fix cargo registry
        run: mkdir -p "$HOME/.cargo/registry" && chown "$(id -u)":"$(id -g)" -R "$HOME/.cargo/registry"
      - name: Build with ink cross
        run: |
          docker run --rm \
          --userns host --user "$(id -u)":"$(id -g)" \
          -v "$HOME/.cargo/registry:/usr/local/cargo/registry" \
          -v ./:/project \
          ghcr.io/cargo-prebuilt/ink-cross:${{ matrix.rust-version }}-${{ matrix.info.target }} \
          build --verbose --workspace --target ${{ matrix.info.target }}
      - name: Artifact
        if: ${{ matrix.rust-version == 'nightly' }}
        uses: actions/upload-artifact@v4
        with:
          name: target-ic-${{ matrix.target }}
          path: |
            target/${{ matrix.target }}/debug/${{ env.bin-name }}

  test-all:
    strategy:
      fail-fast: false
      matrix:
        rust-version: [ nightly ]
        info:
          - os: macos-latest
          - os: ubuntu-latest
    runs-on: ${{ matrix.info.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: dtolnay/rust-toolchain@master
        id: toolchain
        with:
          toolchain: ${{ matrix.rust-version }}
          components: rust-src
      - uses: Swatinem/rust-cache@v2
        with:
          key: test-all
      - name: Buils
        run: RUST_BACKTRACE=1 cargo +${{steps.toolchain.outputs.name}} build --verbose --workspace --locked
      - name: Test
        run: ./test/_test.sh
